version: "2"

services:
  # web:
  #   build: .
  #   command: npm run start
  #   restart: always
  #   volumes:
  #     - ./dist:/server/dist
  #   ports:
  #     - "3000:3000"
  #     - "5858:5858"
  # transpiler:
  #   build: .
  #   command: ["tsc", "-w"]
  #   volumes:
  #     - /server/src
  #     - /server/node_modules
  app:
    build: .
    command: npm run dev
    environment:
      NODE_ENV: "development"
      PORT: 5000
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      # - "0.0.0.0:5000:5000"
      - "5000:5000"
      - "5858:5858"
    # command: sh -c "mkdir -p build && nodemon --delay 500ms --watch dist ./build/authentication-server.js"
  # transpiler:
  #   build: .
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   command: ["tsc", "-w"]
